# -*- coding: utf-8 -*-
"""Innocentia Handani_0806022410010_AlproWeek8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRvkE3qyOUf65CgCTiC73__elwFmB0RI

#1
"""

from collections import deque

#fungsi untuk menjalankan pilihan transaksi
#parameternya adalah choice(pilihan transaksi apa) dan siapa nasabah yang sedang dilayani
def pilihan_transaksi (transaksi,nasabah):
  #saldo nasabah diambil dari data_nasabah sesuai nama nasabah
  saldo_nasabah = data_nasabah.get(nasabah)
  #menggunakan switch case
  match transaksi:
    #tarik tunai
    case 1:
      tarik_saldo = int(input('Masukkan jumlah yang ingin ditarik: '))
      #jika saldo nasabah mencukupi, dapat melakukan tarik saldo
      if saldo_nasabah >= tarik_saldo:
        #kurangi saldo awal dengan jumlah yang ditarik
        data_nasabah[nasabah] -= tarik_saldo
        #simpan saldo update
        saldo_nasabah = data_nasabah[nasabah]
        print(f"{nasabah} berhasil menarik tunai Rp{tarik_saldo:,}.")
        print(f"Saldo sekarang: Rp{saldo_nasabah:,}")
      else:
        print('Saldo tidak mencukupi')
    #cek saldo
    case 2:
      #print nama nasabah dan saldo nasabah saat ini
      print(f'Saldo {nasabah}: Rp{data_nasabah[nasabah]:,}')
    #setor tunai
    case 3:
      setor_saldo = int(input('Masukkan jumlah yang ingin disetor: '))
      #menambahkan saldo awal dengan nilai yang dimasukkan
      data_nasabah[nasabah] += setor_saldo
      #simpan saldo update
      saldo_nasabah = data_nasabah[nasabah]
      print(f'{nasabah} berhasil setor tunai Rp{setor_saldo:,}.')
      print(f'Saldo sekarang: Rp{saldo_nasabah:,}')

n = int(input('Masukkan jumlah nasabah: '))

queue_nasabah = deque()
data_nasabah = {}

for i in range(n):
  nama = input(f'Masukkan nama nasabah {i+1}: ')
  if nama in data_nasabah:
    continue
  saldo_awal = int(input(f'Masukkan saldo awal {nama}: '))
  data_nasabah[nama] = saldo_awal
  queue_nasabah.append(nama)

while queue_nasabah:
  nasabah_dilayani = queue_nasabah.popleft()
  print()
  print(f'Nasabah {nasabah_dilayani} sedang dilayani.')

  while True:
    print()
    print('Pilih transaksi:')
    print('1. Tarik Tunai')
    print('2. Cek Saldo')
    print('3. Setor Tunai')
    print('4. Selesai')
    choice = int(input('Masukkan pilihan Anda: '))
    pilihan_transaksi(choice,nasabah_dilayani)
    if choice == 4:
      print(f'{nasabah_dilayani} telah selesai melakukan transaksi')
      break
print()
print('Antrian Kali ini Telah Selesai')

"""#2"""

#buat fungsi untuk mengecek kata palindrome atau bukan dengan stack/queue
def word_processor(word):
  #buat array kosong untuk iterasi kata
  queue = []
  stack = []
  #iterasi tiap huruf dalam kata
  for char in word:
    #masukkan kedalam array
    queue.append(char)
    stack.append(char)
  #looping akan terus berjalan sebanyak element yang ada dalam array queue
  #elemen queue = stack
  while queue:
    #jika iterasi queue dan stack saat berjalan dan menemukan element yang berbeda
    if queue.pop(0) != stack.pop():
      #bukan palindrome
      return False
  #selain itu benar
  return True

word_processor('radar')

word_processor('hello')

